version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/tictactoe
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tictactoe

    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tictactoe
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database-scripts:/database-scripts
volumes:
  db:
    driver: local
