source 'https://rubygems.org'

gem 'dry-system'
gem 'dry-inflector'

gem 'pry'

gem 'zeitwerk'

gem 'rom'
gem 'rom-sql'
gem 'dry-struct'
gem 'pg'

gem 'rake'

gem 'sinatra'
gem 'sinatra-cross_origin'

gem 'sinatra-activerecord'
gem 'activerecord'

gem 'yaml'

gem 'rails'